repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.5.0"
    hooks:
        - id: check-merge-conflict
        - id: debug-statements
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8